/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_semana7;

/**
 *
 * @author User001
 */

public class FrameListaCita extends javax.swing.JFrame {

    private FrameNuevaCita padre;
    /**
     * Creates new form FrameListaCita
     */
    public FrameListaCita(FrameNuevaCita padre) {
        initComponents();
        this.padre = padre;
    }

    private FrameListaCita() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscarCitaDNIPaciente = new javax.swing.JTextField();
        bttCancekarFLC = new javax.swing.JButton();
        bttBuscarCita = new javax.swing.JButton();
        bttCrearCita = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCita = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarCitaDNIPaciente.setText("jTextField1");
        txtBuscarCitaDNIPaciente.setMaximumSize(new java.awt.Dimension(149, 30));
        txtBuscarCitaDNIPaciente.setMinimumSize(new java.awt.Dimension(149, 30));
        txtBuscarCitaDNIPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCitaDNIPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarCitaDNIPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        bttCancekarFLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 9 (1).png"))); // NOI18N
        bttCancekarFLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancekarFLCActionPerformed(evt);
            }
        });
        jPanel1.add(bttCancekarFLC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        bttBuscarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 8.jpg"))); // NOI18N
        bttBuscarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarCitaActionPerformed(evt);
            }
        });
        jPanel1.add(bttBuscarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        bttCrearCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 10.jpg"))); // NOI18N
        bttCrearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCrearCitaActionPerformed(evt);
            }
        });
        jPanel1.add(bttCrearCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        lstCita.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCita);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 300, 120));

        jLabel3.setText("Ingresa el DNI a buscar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Citas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clinica oeste 1.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarCitaDNIPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCitaDNIPacienteActionPerformed

    }//GEN-LAST:event_txtBuscarCitaDNIPacienteActionPerformed

    private void bttCancekarFLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancekarFLCActionPerformed
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttCancekarFLCActionPerformed

    private void bttBuscarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarCitaActionPerformed

    }//GEN-LAST:event_bttBuscarCitaActionPerformed

    private void bttCrearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCrearCitaActionPerformed
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttCrearCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameListaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameListaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameListaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameListaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameListaCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttBuscarCita;
    private javax.swing.JButton bttCancekarFLC;
    private javax.swing.JButton bttCrearCita;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstCita;
    private javax.swing.JTextField txtBuscarCitaDNIPaciente;
    // End of variables declaration//GEN-END:variables
}
