/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_semana7;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author User001
 */
public class FrameListaPaciente extends javax.swing.JFrame {

    private FrameNuevaCita padre;
    DefaultListModel modele = new DefaultListModel();
    List<Paciente> paciente = new ArrayList<>();
    private List<String> listaDNI = new ArrayList<>();
    public FrameListaPaciente(FrameNuevaCita padre) {
        initComponents();
        this.padre = padre;
    }

    private FrameListaPaciente() {
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscarPacienteDNI = new javax.swing.JTextField();
        bttCancelarFLP = new javax.swing.JButton();
        bttBuscarPacienteDNI = new javax.swing.JButton();
        bttCrearPaciente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPaciente = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarPacienteDNI.setText("jTextField1");
        txtBuscarPacienteDNI.setMaximumSize(new java.awt.Dimension(149, 30));
        txtBuscarPacienteDNI.setMinimumSize(new java.awt.Dimension(149, 30));
        txtBuscarPacienteDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPacienteDNIActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscarPacienteDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        bttCancelarFLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 4.png"))); // NOI18N
        bttCancelarFLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarFLPActionPerformed(evt);
            }
        });
        jPanel1.add(bttCancelarFLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        bttBuscarPacienteDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 2.png"))); // NOI18N
        bttBuscarPacienteDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarPacienteDNIActionPerformed(evt);
            }
        });
        jPanel1.add(bttBuscarPacienteDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        bttCrearPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 10 (1).png"))); // NOI18N
        bttCrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCrearPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(bttCrearPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        lstPaciente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstPaciente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 130));

        jLabel3.setText("Ingresa DNI a buscar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Pacientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clinica oeste 1.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPacienteDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPacienteDNIActionPerformed

    }//GEN-LAST:event_txtBuscarPacienteDNIActionPerformed

    private void bttCancelarFLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarFLPActionPerformed
        this.padre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_bttCancelarFLPActionPerformed

    private void bttCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCrearPacienteActionPerformed
        
        FrameAgregarPaciente ventanacurso = new FrameAgregarPaciente(this);
        ventanacurso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttCrearPacienteActionPerformed

    private void bttBuscarPacienteDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarPacienteDNIActionPerformed
        String dniABuscar = txtBuscarPacienteDNI.getText();
    
    for (int i = 0; i < listaDNI.size(); i++) {
        String dni = listaDNI.get(i);
        if (dni.equalsIgnoreCase(dniABuscar)) {
            // Encontramos el DNI, selecciona el paciente en la lista principal
            lstPaciente.setSelectedIndex(i);
            break; // Salimos del bucle una vez que encontramos el DNI
        }
    }
    }//GEN-LAST:event_bttBuscarPacienteDNIActionPerformed

    public void agregarPaciente(String nombre, String DNI, String Telefono, String Sexo) {
    Paciente nuevoPaciente = new Paciente(nombre, DNI, Telefono, Sexo);
    paciente.add(nuevoPaciente);
    listaDNI.add(DNI);
    modele.addElement(nombre+"| DNI: "+ DNI);
    lstPaciente.setModel(modele);
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameListaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameListaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttBuscarPacienteDNI;
    private javax.swing.JButton bttCancelarFLP;
    private javax.swing.JButton bttCrearPaciente;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPaciente;
    private javax.swing.JTextField txtBuscarPacienteDNI;
    // End of variables declaration//GEN-END:variables
}
