/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_semana7;

/**
 *
 * @author User001
 */
public class FrameAgregarMedico extends javax.swing.JFrame {

    private FrameListaMedico padre;
    public FrameAgregarMedico(FrameListaMedico padre) {
        initComponents();
        this.padre = padre;
    }

    private FrameAgregarMedico() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bttCancelarFAM = new javax.swing.JButton();
        bttCrearMedico = new javax.swing.JButton();
        txtNombreMedico = new javax.swing.JTextField();
        txtCMPMedico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 170, 100));

        bttCancelarFAM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 4.png"))); // NOI18N
        bttCancelarFAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarFAMActionPerformed(evt);
            }
        });
        jPanel1.add(bttCancelarFAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        bttCrearMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 10 (1).png"))); // NOI18N
        bttCrearMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCrearMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(bttCrearMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        txtNombreMedico.setText("jTextField1");
        txtNombreMedico.setMaximumSize(new java.awt.Dimension(149, 30));
        txtNombreMedico.setMinimumSize(new java.awt.Dimension(149, 30));
        txtNombreMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 170, -1));

        txtCMPMedico.setText("jTextField2");
        txtCMPMedico.setMaximumSize(new java.awt.Dimension(149, 30));
        txtCMPMedico.setMinimumSize(new java.awt.Dimension(149, 30));
        jPanel1.add(txtCMPMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, -1));

        jButton1.setText("+");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jButton2.setText("-");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel3.setText("Ingrese los valores del Paciente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clinica oeste 1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCancelarFAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarFAMActionPerformed
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttCancelarFAMActionPerformed

    private void bttCrearMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCrearMedicoActionPerformed
        String nombrePaciente = txtNombreMedico.getText();
        String DNIPaciente = txtCMPMedico.getText();
       
        this.padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttCrearMedicoActionPerformed

    private void txtNombreMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMedicoActionPerformed

    }//GEN-LAST:event_txtNombreMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAgregarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCancelarFAM;
    private javax.swing.JButton bttCrearMedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCMPMedico;
    private javax.swing.JTextField txtNombreMedico;
    // End of variables declaration//GEN-END:variables
}
