/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_semana7;

import javax.swing.DefaultComboBoxModel;
public class FrameAgregarPaciente extends javax.swing.JFrame {

    private FrameListaPaciente padre;
    public FrameAgregarPaciente(FrameListaPaciente padre) {
        initComponents();
        this.padre = padre;
        cbSexoPaciente.setModel(new DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
    }

    private FrameAgregarPaciente() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttCancelarFAP = new javax.swing.JButton();
        bttCrearPaciente = new javax.swing.JButton();
        txtTelefonoPaciente = new javax.swing.JTextField();
        txtNombrePaciente = new javax.swing.JTextField();
        txtDNIPaciente = new javax.swing.JTextField();
        cbSexoPaciente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttCancelarFAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 4.png"))); // NOI18N
        bttCancelarFAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarFAPActionPerformed(evt);
            }
        });
        jPanel1.add(bttCancelarFAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        bttCrearPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Group 10 (1).png"))); // NOI18N
        bttCrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCrearPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(bttCrearPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        txtTelefonoPaciente.setText("jTextField2");
        txtTelefonoPaciente.setMaximumSize(new java.awt.Dimension(149, 30));
        txtTelefonoPaciente.setMinimumSize(new java.awt.Dimension(149, 30));
        jPanel1.add(txtTelefonoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, -1));

        txtNombrePaciente.setText("jTextField1");
        txtNombrePaciente.setMaximumSize(new java.awt.Dimension(149, 30));
        txtNombrePaciente.setMinimumSize(new java.awt.Dimension(149, 30));
        txtNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, -1));

        txtDNIPaciente.setText("jTextField2");
        txtDNIPaciente.setMaximumSize(new java.awt.Dimension(149, 30));
        txtDNIPaciente.setMinimumSize(new java.awt.Dimension(149, 30));
        jPanel1.add(txtDNIPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 170, -1));

        cbSexoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSexoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(cbSexoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel3.setText("Ingrese los valores del Paciente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clinica oeste 1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCrearPacienteActionPerformed
        String nombrePaciente = txtNombrePaciente.getText();
        String DNIPaciente = txtDNIPaciente.getText();
        String TelefonoPaciente = txtTelefonoPaciente.getText();
        String SexoPaciente = (String) cbSexoPaciente.getSelectedItem();

        padre.agregarPaciente(nombrePaciente, DNIPaciente,TelefonoPaciente,SexoPaciente);
        this.padre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_bttCrearPacienteActionPerformed

    private void txtNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteActionPerformed
        
    }//GEN-LAST:event_txtNombrePacienteActionPerformed

    private void bttCancelarFAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarFAPActionPerformed
         this.padre.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_bttCancelarFAPActionPerformed

    private void cbSexoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoPacienteActionPerformed

    }//GEN-LAST:event_cbSexoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAgregarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCancelarFAP;
    private javax.swing.JButton bttCrearPaciente;
    private javax.swing.JComboBox<String> cbSexoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDNIPaciente;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtTelefonoPaciente;
    // End of variables declaration//GEN-END:variables
}
